### ISSUE TITLE
error: Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`

### ISSUE THREAD

**Issue by YIN-Renlong** [davideuler/gpt4-pdf-chatbot-langchain-chromadb#3]
First of all, I appreciate your dedication to this project, but there is a serious problem that needs to be solved in macOS. The installation process is smooth, but when entering http://localhost:3000/ in browser, no matter what questions are entered, after clicking the Enter key, this error message will appear at the bottom of the interface: 

`error: Error: Please install chromadb as a dependency with, e.g. npm install -S chromadb`

Here are the full error codes in Terminal:

`
error: Error: Please install chromadb as a dependency with, e.g. npm install -S chromadb
`
`
    at Chroma.imports (file:///Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/langchain/dist/vectorstores/chroma.js:159:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Chroma.ensureCollection (file:///Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/langchain/dist/vectorstores/chroma.js:61:42)
    at async Chroma.fromExistingCollection (file:///Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/langchain/dist/vectorstores/chroma.js:150:9)
    at async handler (webpack-internal:///(api)/./pages/api/chat.ts:47:53)
    at async Object.apiResolver (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/next-server.js:513:9)
    at async Object.fn (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/next-server.js:815:35)
    at async Router.execute (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/router.js:243:32)
    at async DevServer.runImpl (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/base-server.js:432:29)
    at async DevServer.run (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/dev/next-dev-server.js:814:20)
    at async DevServer.handleRequestImpl (/Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/base-server.js:375:20)
    at async /Users/macosUser1/gpt4-pdf-chatbot-langchain-chromadb/node_modules/next/dist/server/base-server.js:157:99
`

The installed node version:   
`
node -v
v18.17.1
`

The same error appears in several different macs, including Intel and Apple silicon chips.

I tried to install it according to the prompts, but to no avail. Any solution? Thanks

**Comment by tianyilt** [comment]
The same problem,
happened in chat.ts
```
const vectorStore = await Chroma.fromExistingCollection(
      new OpenAIEmbeddings({}),
      {
        collectionName: process.env.COLLECTION_NAME,
        url: 'xxxxxxxxx',
      },
    );
```

**Comment by vasudharao08** [comment]
Did you manage to resolve this? @YIN-Renlong  @tianyilt

**Comment by vasudharao08** [comment]
NVM: Rolling back to 1.5.6 fixes this

**Comment by vasudharao08** [comment]
@YIN-Renlong I started getting this error now : "Required parameter collectionId was null or undefined when calling getNearestNeighbors". Any suggestions?

**Comment by YIN-Renlong** [comment]
> @YIN-Renlong I started getting this error now : "Required parameter collectionId was null or undefined when calling getNearestNeighbors". Any suggestions?

@vasudharao08 Hello, I apologize for not being able to help more, but the difficulty of configuring chromadb locally has caused me to completely forsake this version. Please refer to this version https://github.com/mayooear/gpt4-pdf-chatbot-langchain

**Comment by vasudharao08** [comment]
Actually I just resolved this, looks like it was the ChromaDB version error. Upgrading it solves the problem!

**Comment by george-sagaiq** [comment]
If it helps - here is how I worked around this problem: https://github.com/langchain-ai/langchainjs/issues/2637#issuecomment-2552735141
